<?php

$users = [
    [
        'name' => 'Jakub  JabĹ‚oĹ„ski',
        'email' => 'jakub.jaboski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'JarosĹ‚aw Adamczyk',
        'email' => 'jarosaw.adamczyk@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Urszula  Dynowska',
        'email' => 'urszula.dynowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD',
        'parent_hierarchical_id' => 'GDJJ/JA',
    ],
    [
        'name' => 'Malgorzata Sienkiewicz-Ĺuczyn',
        'email' => 'malgorzata.sienkiewiczuczyn@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS',
        'parent_hierarchical_id' => 'GDJJ/JA/UD',
    ],
    [
        'name' => 'RafaĹ‚ Choroszynski',
        'email' => 'rafa.choroszynski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/RC',
        'parent_hierarchical_id' => 'GDJJ/JA',
    ],
    [
        'name' => 'Patryk Szerniewicz',
        'email' => 'patryk.szerniewicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/RC/PS',
        'parent_hierarchical_id' => 'GDJJ/JA/RC',
    ],
    [
        'name' => 'Piotr  Pstrocki',
        'email' => 'piotr.pstrocki@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/RC/PP',
        'parent_hierarchical_id' => 'GDJJ/JA/RC',
    ],
    [
        'name' => 'Joanna (Darek) Lisowska',
        'email' => 'joannadarek.lisowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/RC/JL',
        'parent_hierarchical_id' => 'GDJJ/JA/RC',
    ],
    [
        'name' => 'Alicja Lietz',
        'email' => 'alicja.lietz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/AL',
        'parent_hierarchical_id' => 'GDJJ/JA',
    ],
    [
        'name' => 'Natalia Kropez vel Kropacz',
        'email' => 'natalia.kropezvelkropacz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Karol Jackiewicz',
        'email' => 'karol.jackiewicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/KJ',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Krzysztof Rimpel',
        'email' => 'krzysztof.rimpel@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/KR',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Daniel Orzechowski',
        'email' => 'daniel.orzechowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS/DO',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'Jacek Wojtyra',
        'email' => 'jacek.wojtyra@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/JW',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'PaweĹ‚  Pikiewicz',
        'email' => 'pawe.pikiewicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/PP',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Ireneusz Damps',
        'email' => 'ireneusz.damps@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/ID',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'PaweĹ‚ Pikiewicz',
        'email' => 'pawe.pikiewicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/PP',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Ireneusz Damps',
        'email' => 'ireneusz.damps@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/PP',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Mateusz Tyl',
        'email' => 'mateusz.tyl@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TL/',
        'parent_hierarchical_id' => 'GDJJ/TL',
    ],
    [
        'name' => 'Magdalena Kowalska',
        'email' => 'magdalena.kowalska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TL/MK',
        'parent_hierarchical_id' => 'GDJJ/MT',
    ],
    [
        'name' => 'Tomasz Lasowski',
        'email' => 'tomasz.lasowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TL',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Maciej JabĹ‚oĹ„ski',
        'email' => 'maciej.jaboski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/MJ',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Tymoteusz Pawlikowski',
        'email' => 'tymoteusz.pawlikowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TP',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Maksym Yakymchuk',
        'email' => 'maksym.yakymchuk@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TP/MY',
        'parent_hierarchical_id' => 'GDJJ/TP',
    ],
    [
        'name' => 'Szczepan Dziwosz (str. KIELCE)',
        'email' => 'szczepan.dziwoszstrkielce@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Konrad Adach',
        'email' => 'konrad.adach@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/KA',
        'parent_hierarchical_id' => 'GDJJ/SK',
    ],
    [
        'name' => 'Aleksandra Grabowska',
        'email' => 'aleksandra.grabowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/AG',
        'parent_hierarchical_id' => 'GDJJ/SK',
    ],
    [
        'name' => 'Dominika Raczkowska',
        'email' => 'dominika.raczkowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/AG/DR',
        'parent_hierarchical_id' => 'GDJJ/SK/AG',
    ],
    [
        'name' => 'Olga Ĺ»ochowska',
        'email' => 'olga.ochowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/AG/OZ',
        'parent_hierarchical_id' => 'GDJJ/SK/AG',
    ],
    [
        'name' => 'Maciej Kaczan',
        'email' => 'maciej.kaczan@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/AG/MK',
        'parent_hierarchical_id' => 'GDJJ/SK/AG',
    ],
    [
        'name' => 'PaweĹ‚ WadyĹ„ski',
        'email' => 'pawe.wadyski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/SK/AG/PW',
        'parent_hierarchical_id' => 'GDJJ/SK/AG',
    ],
    [
        'name' => 'Krzysztof Kortas',
        'email' => 'krzysztof.kortas@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TP/KK',
        'parent_hierarchical_id' => 'GDJJ/TP',
    ],
    [
        'name' => 'Karolina Galera',
        'email' => 'karolina.galera@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/KG',
        'parent_hierarchical_id' => 'GDJJ/JA/RC',
    ],
    [
        'name' => 'Jakub  Sowa',
        'email' => 'jakub.sowa@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/JS',
        'parent_hierarchical_id' => 'GDJJ/JA',
    ],
    [
        'name' => 'Kacper ReĹ„ski',
        'email' => 'kacper.reski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Hubert Witowski',
        'email' => 'hubert.witowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TP/HW',
        'parent_hierarchical_id' => 'GDJJ/TP',
    ],
    [
        'name' => 'Andrzej Bal',
        'email' => 'andrzej.bal@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJ/TP/HW/AB',
        'parent_hierarchical_id' => 'GDJJ/TP/HW',
    ],
    [
        'name' => 'Piotr  SkaĹ‚ecki',
        'email' => 'piotr.skaecki@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/PS',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'PaweĹ‚  LubiĹ„ski',
        'email' => 'pawe.lubiski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/PL',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'PrzemysĹ‚aw Wolski',
        'email' => 'przemysaw.wolski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/PW',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'Piotr  GĹ‚ogowski',
        'email' => 'piotr.gogowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/PG',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Ĺukasz Szablewski',
        'email' => 'ukasz.szablewski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/LS',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'RafaĹ‚  Wojtas',
        'email' => 'rafa.wojtas@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS/RW',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'Piotr  Amanowicz',
        'email' => 'piotr.amanowicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS/PA',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'MaĹ‚gorzata Cholewicka',
        'email' => 'magorzata.cholewicka@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/RC/MC',
        'parent_hierarchical_id' => 'GDJJ/JA/RC',
    ],
    [
        'name' => 'Alina Wiczarska',
        'email' => 'alina.wiczarska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/MT/AW',
        'parent_hierarchical_id' => 'GDJJ/MT',
    ],
    [
        'name' => 'Marzanna Szarolkiewicz',
        'email' => 'marzanna.szarolkiewicz@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1',
        'parent_hierarchical_id' => 'GDJJ/JA/UD',
    ],
    [
        'name' => 'Mariola  GwizdaĹ‚a',
        'email' => 'mariola.gwizdaa@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'Paulina LeoĹ„ska',
        'email' => 'paulina.leoska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/PL',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'Agnieszka Seremak',
        'email' => 'agnieszka.seremak@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/KR/AS',
        'parent_hierarchical_id' => 'GDJJ/KR',
    ],
    [
        'name' => 'Robert Ogonowski',
        'email' => 'robert.ogonowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1/RO',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS1',
    ],
    [
        'name' => 'Martyna Kwiatkowska',
        'email' => 'martyna.kwiatkowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1/MK',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS1',
    ],
    [
        'name' => 'MikoĹ‚aj Skonieczka',
        'email' => 'mikoaj.skonieczka@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/NK/MS',
        'parent_hierarchical_id' => 'GDJJ/NK',
    ],
    [
        'name' => 'Anna Drywa',
        'email' => 'anna.drywa@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/AD',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Aleksandra  Koszczyc',
        'email' => 'aleksandra.koszczyc@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/AK',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Sabrina Gralak',
        'email' => 'sabrina.gralak@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/SG',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Oliwia  Mielewczyk',
        'email' => 'oliwia.mielewczyk@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/OM',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Ewelina  Muttka',
        'email' => 'ewelina.muttka@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/EM',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Anna Quirini',
        'email' => 'anna.quirini@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/AQ',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Patryk GwizdaĹ‚a',
        'email' => 'patryk.gwizdaa@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/PG',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Dariusz  MiroĹ„ski',
        'email' => 'dariusz.miroski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/DG',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Natalia Malinowska',
        'email' => 'natalia.malinowska@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MG/NM',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MG',
    ],
    [
        'name' => 'Krzysztof Grygierzec',
        'email' => 'krzysztof.grygierzec@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1/KG',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'Piotr  Dymowski',
        'email' => 'piotr.dymowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/PD',
        'parent_hierarchical_id' => 'GDJJ',
    ],
    [
        'name' => 'JarosĹ‚aw PawĹ‚owski',
        'email' => 'jarosaw.pawowski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1/JP',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'MichaĹ‚ NizgĂłrski',
        'email' => 'micha.nizglrski@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/UD/MS1/MN',
        'parent_hierarchical_id' => 'GDJJ/JA/UD/MS',
    ],
    [
        'name' => 'Kamil Buczak',
        'email' => 'kamil.buczak@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/JA/KB',
        'parent_hierarchical_id' => 'GDJJ/JA',
    ],
    [
        'name' => 'Serchii Ivanchenko',
        'email' => 'serchii.ivanchenko@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/TP/KK/SI',
        'parent_hierarchical_id' => 'GDJJ/KK',
    ],
    [
        'name' => 'Anna  Safader-Szkudlarek',
        'email' => 'anna.safaderszkudlarek@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'MH/AS',
        'parent_hierarchical_id' => 'WAAG/TM',
    ],
    [
        'name' => 'PrzemysĹ‚aw Zych',
        'email' => 'przemysaw.zych@stratton-prime.pl',
        'rank' => 'agent',
        'hierarchical_id' => 'GDJJ/PD/PZ',
        'parent_hierarchical_id' => 'GDJJ/PD/',
    ],
];

