export const contactSources = [
  'Kontakt własny',
  'Cold calling',
  'Polecenie od innego klienta',
  'Przypadkowa rozmowa',
]

export const industries = [
  "Uprawy rolne, chów i hodowla zwierząt, łowiectwo, włączając działalność usługową",
  "Leśnictwo i pozyskiwanie drewna",
  "Rybactwo",
  "Wydobywanie węgla kamiennego i węgla brunatnego (lignitu)",
  "Górnictwo ropy naftowej i gazu ziemnego",
  "Górnictwo rud metali",
  "Pozostałe górnictwo i wydobywanie",
  "Usługi wspomagające górnictwo i wydobywanie",
  "Produkcja art. spożywczych",
  "Produkcja napojów",
  "Produkcja wyrobów tytoniowych",
  "Produkcja wyrobów tekstylnych",
  "Produkcja odzieży",
  "Produkcja skór i wyrobów ze skór wyprawionych",
  "Produkcja wyrobów z drewna oraz korka, z wyłączeniem mebli; Produkcja wyrobów ze słomy i materiałów używanych do wyplatania",
  "Produkcja papieru i wyrobów z papieru",
  "Poligrafia i reprodukcja zapisanych nośników informacji",
  "Wytwarzanie i przetwarzanie koksu i produktów rafinacji ropy naftowej",
  "Produkcja chemikaliów i wyrobów chemicznych",
  "Produkcja podstawowych substancji farmaceutycznych oraz leków i pozostałych wyrobów farmaceutycznych",
  "Produkcja wyrobów z gumy i tworzyw sztucznych",
  "Produkcja wyrobów z pozostałych mineralnych surowców niemetalicznych",
  "Produkcja metali",
  "Produkcja metalowych wyrobów gotowych, z wyłączeniem maszyn i urządzeń",
  "Produkcja komputerów, wyrobów elektronicznych i optycznych",
  "Produkcja urządzeń elektrycznych",
  "Produkcja maszyn i urządzeń, gdzie indziej niesklasyfikowana",
  "Produkcja pojazdów samochodowych, przyczep i naczep, z wyłączeniem motocykli",
  "Produkcja pozostałego sprzętu transportowego",
  "Produkcja mebli",
  "Pozostała produkcja wyrobów",
  "Naprawa, konserwacja i instalowanie maszyn i urządzeń",
  "Wytwarzanie i zaopatrywanie w energię elektryczną, gaz, parę wodną, gorącą wodę i powietrze do układów klimatyzacyjnych",
  "Pobór, uzdatnianie i dostarczanie wody",
  "Odprowadzanie i oczyszczanie ścieków",
  "Zbieranie, przetwarzanie i unieszkodliwianie odpadów oraz odzysk surowców",
  "Rekultywacją i pozostałe usługi związane z gospodarką odpadami",
  "Roboty budowlane związane ze wznoszeniem budynków",
  "Roboty związane z budową obiektów inżynierii lądowej i wodnej",
  "Roboty budowlane specjalistyczne",
  "Handel hurtowy i detaliczny pojazdami samochodowymi; Naprawa pojazdów samochodowych",
  "Handel hurtowy (bez pojazdów samochodowych)",
  "Handel detaliczny (bez pojazdów samochodowych)",
  "Transport lądowy oraz rurociągowy",
  "Transport wodny",
  "Transport lotniczy",
  "Magazynowanie i usługi wspomagające transport",
  "Działalność pocztowa i kurierska",
  "Zakwaterowanie",
  "Wyżywienie",
  "Działalność wydawnicza",
  "Działalność filmowa, telewizyjna, dźwiękowa i muzyczna",
  "Nadawanie programów telewizyjnych i radiowych",
  "Telekomunikacja",
  "Oprogramowanie i doradztwo w zakresie informatyki",
  "Zarządzanie stronami WWW, przetwarzanie danych i hosting",
  "Usługi finansowe z wyłączeniem ubezpieczeń i funduszów emerytalnych",
  "Ubezpieczenia, reasekuracja i fundusze emerytalne, z wyłączeniem obowiązkowego ubezpieczenia społecznego",
  "Usługi objęrem pośrednictwem finansowym",
  "Obsługa rynku nieruchomości",
  "Usługi prawnicze, rachunkowo-księgowe i doradztwo podatkowe",
  "Działalność firm centralnych i doradztwo związane z zarządzaniem",
  "Architektura, inżynieria, badania i analizy techniczne",
  "Badania naukowe i prace rozwojowe",
  "Reklama, badanie rynku i opinii publicznej",
  "Projektowanie, fotografia, tłumaczenia, działalność profesjonalna",
  "Weterynaria",
  "Wynajem i dzierżawa",
  "Zatrudnienie",
  "Turystyka",
  "Usługi detektywistyczne i ochroniarskie",
  "Sprzątanie budynków i gospodarowanie terenami zieleni",
  "Administracja biurowa i wspomaganie prowadzenia działalności gospodarczej",
  "Administracja publiczna, obrona narodowa i obowiązkowe zabezpieczenia społeczne",
  "Edukacja",
  "Opieka zdrowotna",
  "Pomoc społeczna (z zakwaterowaniem)",
  "Pomoc społeczna (bez zakwaterowania)",
  "Kultura i rozrywka",
  "Biblioteki, archiwa, muzea, zoo oraz inne obiekty kulturalne",
  "Gry losowe i zakłady wzajemne",
  "Sport, rozrywka i rekreacja",
  "Działalność organizacji członkowskich",
  "Naprawa komputerów i artykułów osobistych oraz domowych",
  "Pozostała indywidualna działalność usługowa",
]
