<?php

return [
    'base_url' => env('KC_BASE_URL', ''),
    'realm' => env('KC_REALM', ''),
    'client_id' => env('KC_CLIENT_ID', ''),
    'client_secret' => env('KC_CLIENT_SECRET'),
    'admin_client_id' => env('KC_ADMIN_CLIENT_ID'),
    'admin_client_secret' => env('KC_ADMIN_CLIENT_SECRET'),
    'sync_enabled' => env('KC_SYNC_ENABLED', false),
    'admin_timeout' => env('KC_ADMIN_TIMEOUT', 10),
    'admin_page_size' => env('KC_ADMIN_PAGE_SIZE', 100),
    'admin_max_users' => env('KC_ADMIN_MAX_USERS', 5000),

    'issuer' => env('KC_ISSUER'),
    'jwks_url' => env('KC_JWKS_URL'),
    'audience' => env('KC_AUDIENCE'),

    // Optional role mapping from Keycloak role -> local role code.
    'role_map' => [
        'admin' => 'ADMIN',
        'director' => 'DIRECTOR',
        'manager' => 'MANAGER',
        'sales' => 'SALES',
        'client_hr' => 'CLIENT_HR',
        // 'kc-advisor' => 'advisor',
    ],

    // Role priority used when multiple roles exist in token.
    'role_priority' => [
        'ADMIN',
        'DIRECTOR',
        'MANAGER',
        'SALES',
        'CLIENT_HR',
        'admin',
        'director',
        'manager',
        'sales',
        'client_hr',
        'advisor',
    ],

    // Optional mapping to sync permissions for local roles.
    'role_permissions' => [
        'ADMIN' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'consents.create',
            'consents.update',
            'consents.delete',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'documents.view',
            'documents.update',
            'calculator-configs.view',
            'calculator-configs.create',
            'calculator-configs.update',
        ],
        'DIRECTOR' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'MANAGER' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'SALES' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'CLIENT_HR' => [
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'admin' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'consents.create',
            'consents.update',
            'consents.delete',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'documents.view',
            'documents.update',
            'calculator-configs.view',
            'calculator-configs.create',
            'calculator-configs.update',
        ],
        'director' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'manager' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'sales' => [
            'clients.view',
            'clients.create',
            'client-contacts.view',
            'client-contacts.create',
            'client-contacts.update',
            'client-contacts.delete',
            'consents.view',
            'client-consents.view',
            'client-consents.create',
            'client-consents.update',
            'client-consents.delete',
            'meetings.view',
            'meetings.create',
            'meeting-analyses.view',
            'meeting-analyses.create',
            'calculations.view',
            'calculations.create',
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
        'client_hr' => [
            'notifications.view',
            'notifications.create',
            'notifications.update',
            'calculator-configs.view',
        ],
    ],

    // Cache TTL for JWKS in seconds.
    'jwks_cache_ttl' => env('KC_JWKS_CACHE_TTL', 3600),

    // Root group path for team groups.
    'teams_root' => env('KC_TEAMS_ROOT', '/teams'),

    // Email actions to trigger on user creation (comma-separated).
    'invite_actions' => env('KC_INVITE_ACTIONS', 'VERIFY_EMAIL,UPDATE_PASSWORD'),
    'invite_lifespan' => env('KC_INVITE_LIFESPAN', 86400),
];
