<script setup lang="ts">
import { computed } from 'vue'
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTrendingUpIcon,
  ArrowRightOnRectangleIcon,
  BanknotesIcon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  CalculatorIcon,
  ChartBarIcon,
  ChartPieIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CircleStackIcon,
  ClockIcon,
  Cog6ToothIcon,
  CurrencyDollarIcon,
  DocumentTextIcon,
  DocumentDuplicateIcon,
  EyeIcon,
  ExclamationTriangleIcon,
  EnvelopeIcon,
  FunnelIcon,
  FolderIcon,
  HomeIcon,
  HomeModernIcon,
  IdentificationIcon,
  InformationCircleIcon,
  ListBulletIcon,
  NumberedListIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  PencilSquareIcon,
  PhoneIcon,
  PrinterIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  TrophyIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserPlusIcon,
  XMarkIcon,
  XCircleIcon,
  ScaleIcon,
  VideoCameraIcon,
  PresentationChartLineIcon,
  PlayIcon,
  TrashIcon,
  PlusIcon,
  PaperAirplaneIcon,
  CheckIcon,
  InboxIcon,
  EllipsisHorizontalIcon,
  PaperClipIcon,
  CameraIcon,
  StarIcon,
  ExclamationCircleIcon,
  CloudArrowUpIcon,
  ArrowDownTrayIcon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3Icon,
  QueueListIcon,
  ChatBubbleLeftRightIcon
} from '@heroicons/vue/24/outline'

const props = withDefaults(
  defineProps<{
    name: string
    class?: string
  }>(),
  {
    class: 'w-5 h-5',
  }
)

const iconMap: Record<string, any> = {
  dashboard: HomeIcon,
  'chart-line': ChartBarIcon,
  'chart-pie': ChartPieIcon,
  'arrow-trending-up': ArrowTrendingUpIcon,
  'cloud-arrow-up': CloudArrowUpIcon,
  'arrow-down-tray': ArrowDownTrayIcon,
  users: UserGroupIcon,
  'people-group': UserGroupIcon,
  'people-roof': HomeModernIcon,
  'address-book': IdentificationIcon,
  sitemap: HomeModernIcon,
  briefcase: BriefcaseIcon,
  invoice: DocumentTextIcon,
  copy: DocumentDuplicateIcon,
  duplicate: DocumentDuplicateIcon,
  sliders: AdjustmentsHorizontalIcon,
  signature: SparklesIcon,
  trophy: TrophyIcon,
  gear: Cog6ToothIcon,
  wallet: BanknotesIcon,
  medal: TrophyIcon,
  award: TrophyIcon,
  calculator: CalculatorIcon,
  'hand-holding-dollar': BanknotesIcon,
  oil: CircleStackIcon,
  coins: CircleStackIcon,
  dollar: CurrencyDollarIcon,
  calendar: CalendarDaysIcon,
  envelope: EnvelopeIcon,
  mail: EnvelopeIcon,
  'paper-airplane': PaperAirplaneIcon,
  'book-open': BookOpenIcon,
  search: MagnifyingGlassIcon,
  bell: BellIcon,
  logout: ArrowRightOnRectangleIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-down': ChevronDownIcon,
  'arrow-left': ArrowLeftIcon,
  refresh: ArrowPathIcon,
  list: ListBulletIcon,
  clock: ClockIcon,
  filter: FunnelIcon,
  layers: Squares2X2Icon,
  'shield-check': ShieldCheckIcon,
  'graduation-cap': AcademicCapIcon,
  'user-plus': UserPlusIcon,
  plus: PlusIcon,
  stopwatch: ClockIcon,
  'file-invoice-dollar': DocumentTextIcon,
  'document-text': DocumentTextIcon,
  eye: EyeIcon,
  folder: FolderIcon,
  'folder-open': FolderIcon,
  user: UserIcon,
  'user-tie': UserCircleIcon,
  bolt: BoltIcon,
  ghost: QuestionMarkCircleIcon,
  info: InformationCircleIcon,
  'arrow-right': ArrowRightIcon,
  xmark: XMarkIcon,
  'x-circle': XCircleIcon,
  'check-circle': CheckCircleIcon,
  check: CheckIcon,
  'exclamation-triangle': ExclamationTriangleIcon,
  'exclamation-circle': ExclamationCircleIcon,
  'lock-closed': LockClosedIcon,
  building: BuildingOffice2Icon,
  phone: PhoneIcon,
  printer: PrinterIcon,
  'pencil-square': PencilSquareIcon,
  pencil: PencilSquareIcon,
  edit: PencilSquareIcon,
  trash: TrashIcon,
  'scale': ScaleIcon,
  'video-camera': VideoCameraIcon,
  camera: CameraIcon,
  'presentation-chart-line': PresentationChartLineIcon,
  'play': PlayIcon,
  inbox: InboxIcon,
  'dots-horizontal': EllipsisHorizontalIcon,
  paperclip: PaperClipIcon,
  star: StarIcon,
  'file-contract': IdentificationIcon,
  'file-pdf': DocumentTextIcon,
  'file-excel': CircleStackIcon,
  table: ListBulletIcon,
  banknote: BanknotesIcon,
  'align-left': Bars3BottomLeftIcon,
  'align-right': Bars3BottomRightIcon,
  'align-center': Bars3Icon,
  'align-justify': QueueListIcon,
  'list-bullet': ListBulletIcon,
  'list-ordered': NumberedListIcon,
  'chat-bubble': ChatBubbleLeftRightIcon
}

const icon = computed(() => iconMap[props.name] || QuestionMarkCircleIcon)
</script>

<template>
  <component :is="icon" :class="props.class" aria-hidden="true" />
</template>
