<script setup lang="ts">
import { computed } from 'vue'
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTrendingUpIcon,
  ArrowRightOnRectangleIcon,
  BanknotesIcon,
  BellIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  CalculatorIcon,
  ChartBarIcon,
  ChartPieIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  Cog6ToothIcon,
  DocumentTextIcon,
  EyeIcon,
  ExclamationTriangleIcon,
  EnvelopeIcon,
  FunnelIcon,
  FolderIcon,
  HomeIcon,
  HomeModernIcon,
  IdentificationIcon,
  InformationCircleIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  PencilSquareIcon,
  PhoneIcon,
  PrinterIcon,
  QuestionMarkCircleIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  TrophyIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserPlusIcon,
  XMarkIcon,
  XCircleIcon,
} from '@heroicons/vue/24/outline'

const props = withDefaults(
  defineProps<{
    name: string
    class?: string
  }>(),
  {
    class: 'w-5 h-5',
  }
)

const iconMap: Record<string, any> = {
  dashboard: HomeIcon,
  'chart-line': ChartBarIcon,
  'chart-pie': ChartPieIcon,
  'arrow-trending-up': ArrowTrendingUpIcon,
  users: UserGroupIcon,
  'people-group': UserGroupIcon,
  'people-roof': HomeModernIcon,
  'address-book': IdentificationIcon,
  sitemap: HomeModernIcon,
  briefcase: BriefcaseIcon,
  invoice: DocumentTextIcon,
  sliders: AdjustmentsHorizontalIcon,
  signature: SparklesIcon,
  trophy: TrophyIcon,
  gear: Cog6ToothIcon,
  wallet: BanknotesIcon,
  medal: TrophyIcon,
  award: TrophyIcon,
  calculator: CalculatorIcon,
  'hand-holding-dollar': BanknotesIcon,
  calendar: CalendarDaysIcon,
  envelope: EnvelopeIcon,
  'book-open': BookOpenIcon,
  search: MagnifyingGlassIcon,
  bell: BellIcon,
  logout: ArrowRightOnRectangleIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-down': ChevronDownIcon,
  'arrow-left': ArrowLeftIcon,
  refresh: ArrowPathIcon,
  list: ListBulletIcon,
  clock: ClockIcon,
  filter: FunnelIcon,
  layers: Squares2X2Icon,
  'shield-check': ShieldCheckIcon,
  'graduation-cap': AcademicCapIcon,
  'user-plus': UserPlusIcon,
  stopwatch: ClockIcon,
  'file-invoice-dollar': DocumentTextIcon,
  'document-text': DocumentTextIcon,
  eye: EyeIcon,
  folder: FolderIcon,
  user: UserIcon,
  'user-tie': UserCircleIcon,
  bolt: BoltIcon,
  ghost: QuestionMarkCircleIcon,
  info: InformationCircleIcon,
  'arrow-right': ArrowRightIcon,
  xmark: XMarkIcon,
  'x-circle': XCircleIcon,
  'check-circle': CheckCircleIcon,
  'exclamation-triangle': ExclamationTriangleIcon,
  'lock-closed': LockClosedIcon,
  building: BuildingOffice2Icon,
  phone: PhoneIcon,
  printer: PrinterIcon,
  'pencil-square': PencilSquareIcon,
}

const icon = computed(() => iconMap[props.name] || QuestionMarkCircleIcon)
</script>

<template>
  <component :is="icon" :class="props.class" aria-hidden="true" />
</template>
